grafana:
  enabled: true

loki:
  enabled: true

fluentd:
  enabled: true
  config:
    loki_url: "http://loki:3100"
    flush_interval: 5s
    flush_at_shutdown: true

prometheus:
  enabled: true
  config:
    global:
      scrape_interval: 5s
    sources:
      - name: grafana
        targets:
          - "grafana:3000"
      - name: loki
        targets:
          - "loki:3100"