apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
data:
  prmetheus.yaml: |-
    global:
      scrape_interval: {{ .Values.grafana.config.global.scrape_interval}}
      scrape_timeout: {{ .Values.grafana.config.global.scrape_timeout}}

    scrape_configs:
    {{- range .Values.grafana.config.sources }}
      - job_name: {{ .name }}
        static_configs:
          - targets: [{{ join "," .targets }}]
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  app: grafana
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: {{ .Chart.Name }}-grafana
        image: grafana/grafana