apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-conf
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
data:
  local-config.yaml: |-
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_server_max_recv_msg_size: 16777216

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    ruler:
      alertmanager_url: http://localhost:9093

    ingester:
      chunk_block_size: 104857600

    limits_config:
      enforce_metric_name: false
      max_query_length: "72h"
      max_query_parallelism: 16
      ingestion_rate_mb: 65536

---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  {{ if .Values.loki.nodeport -}}
  type: NodePort
  {{ end -}}
  ports:
    - port: 3100
      targetPort: 3100
      {{ if .Values.loki.nodeport -}}
      nodePort: {{ .Values.loki.nodeport }}
      {{ end -}}
      protocol: TCP
      name: http
  selector:
    app: loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: loki
  replicas: 1
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: {{ .Chart.Name }}-loki
        image: grafana/loki
        volumeMounts:
          - name: loki-conf
            mountPath: /etc/loki
            readOnly: true
      volumes:
        - name: loki-conf
          configMap:
            name: loki-conf