apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  {{ if .Values.loki.nodeport -}}
  type: NodePort
  {{ end -}}
  ports:
    - port: 3100
      targetPort: 3100
      {{ if .Values.loki.nodeport -}}
      nodePort: 30101
      {{ end -}}
      protocol: TCP
      name: http
  selector:
    app: loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: loki
  replicas: 1
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: {{ .Chart.Name }}-loki
        image: grafana/loki