apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    app: loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  app: loki
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: loki
  replicas: 1
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: {{ .Chart.Name }}-loki
        image: grafana/loki